version: '3.1'
services:
  leaf-server-snowflake:
    image: leaf-server-snowflake
    container_name: leaf-server-snowflake
    ports:
      - 8003:8080
      - 8182:2182
    depends_on:
      - leaf-zookeeper
    networks:
      - leaf_net

  leaf-server:
    image: leaf-server
    container_name: leaf-server
    ports:
      - 8004:8080
      - 8183:2182
    networks:
      - leaf_net
      
  leaf-zookeeper:
    image: zookeeper:3.4
    container_name: leaf-zookeeper
    hostname: leaf-zookeeper
    ports:
      - 8181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=leaf-zookeeper:2888:3888
    networks:
      - leaf_net
   
networks:
   leaf_net: